apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: task-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-3
  template:
    metadata:
      labels:
        app: task-3
    spec:
      containers:
        - name: nginx-task-3
          image: nginx:1.23.4-alpine
          ports:
            - containerPort: 80
